spring.datasource.url: jdbc:h2:file:./operaton-h2-database-order

operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    generic-properties:
      properties:
        historyTimeToLive: P1D

kafka:
  bootstrap-address: localhost:9092
  trusted-packages: ch.unisg.scs.edpo.order.dto;
  topics:
    order-manufacture: order.manufacture.v1
    order-complete: order.complete.v1
    info: info.v1
    error: error.v1

spring:
  kafka:
    bootstrap-servers: ${kafka.bootstrap-address}
    consumer:
      group-id: order-service-correlation
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer




