bootstrap.servers=localhost:9091,localhost:9092,localhost:9093

auto.offset.reset=earliest
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=ch.unisg.scs.JavaDeserializer
group.id=group1
