bootstrap.servers=localhost:9091,localhost:9092,localhost:9093

key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=ch.unisg.scs.JavaSerializer
acks=all
retries=2147483647
delivery.timeout.ms=120000
request.timeout.ms=100000
retry.backoff.ms=500
metadata.max.age.ms=20000


