# MQTT Configuration
mqtt.broker-uri=tcp://localhost:1883
mqtt.topic=distance

# Inventory Service
edpo.inventory.url=http://localhost:8000

# Color Sensor Service
edpo.sensor.color.url=http://localhost:8081

# Robot Service
edpo.robot.right.url=http://localhost:5000
edpo.robot.left.url=http://localhost:5001
