# Spring Boot Configuration
spring.application.name=factory
spring.datasource.url=jdbc:h2:file:./operaton-h2-database
spring.kafka.bootstrap-servers=localhost:9092

# Operaton Configuration
operaton.bpm.admin-user.id=me
operaton.bpm.admin-user.password=em

# MQTT Configuration
mqtt.broker-uri=tcp://192.168.0.20:1883
mqtt.client-id=factory-service
mqtt.topic="Tinkerforge_Conveyor_distance_IR_short_2a7C"

# Inventory Service
edpo.inventory.url=http://localhost:8000

# Color Sensor Service
edpo.sensor.color.url=http://192.168.0.120:80

# Robot Service
# TODO: insert actual IP address of the computer running the service
edpo.robot.right.url=http://192.168.0.2:5000
edpo.robot.left.url=http://192.168.0.2:5000
