# MQTT Configuration
mqtt:
  broker-uri: tcp://localhost:1883
  client-id: factory-service
  username: ftsim
  password: unisg
  topic: distance-sensor

edpo:
  # Color Sensor Service
  sensor.color.url: http://localhost:8202