# Spring Boot Configuration
spring.application.name=factory
spring.datasource.url=jdbc:h2:file:./operaton-h2-database
spring.kafka.bootstrap-servers=localhost:9092

# Operaton Configuration
operaton.bpm.admin-user.id=me
operaton.bpm.admin-user.password=em
